name: Coverage
on: push
jobs:
  coverage:
    name: Upload to CodeCov
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2.2.1
      with:
        python-version: '3.9'
        architecture: x64

    - name: Setup Nox
      run: pip install nox==2020.8.22

    - name: Setup Poetry
      run: pip install poetry==1.1.4

    - run: nox --sessions tests-3.9 coverage
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
